### ISSUE TITLE
Isomorphism explanation, enum confusion

### ISSUE THREAD

**Issue by bollu** [neongreen/artyom.me#18]
Hello,
First of all, thanks for the great series :)

I'm trying to understand the note about `enum` in [lens over tea 4](https://artyom.me/lens-over-tea-4). Specifically, this part:

> Now let's consider 2 cases – the first is when we use it to turn `s` into `a`, the second is when we use  the iso to turn `b` into `t`. The definition we already have works well enough for the former case, but in the latter case s doesn't even exist:

```haskell
enum f = \_ -> fromEnum <$> f ???
```

I don't understand what you mean by saying "turn the `b` into the `t`".

From what I understand, 

```haskell
enum :: Lens' Int a
enum :: Lens Int Int a a ~= Lens s t a b
b -> t :: a -> Int
```

why is this not a valid candidate?

```haskell
enum_rev :: Lens' a Int
enum_rev f a = toEnum <$> f (fromEnum a)
```

**Comment by neongreen** [comment]
> I don't understand what you mean by saying "turn the b into the t".

We want to use the same thing (`enum`) both for going one way (`Int -> a`) and the other way (`a -> Int`). In particular, for `enum` `“s” = “t” = Int` and `“a” = “b” = a`.

When you try to use `enum` in the other direction, you can't possibly provide an `Int` to it (because the `Int` is what you want to get). Thus I replace things that depend on `s` with question marks:

```
enum f = \s -> fromEnum <$> f (toEnum s)

enum f = \??? -> fromEnum <$> f (toEnum ???)
```

Since nothing can be in place in those question marks, the first one has to be a wildcard and the second one has to be `undefined`:

```
enum f = \_ -> fromEnum <$> f (toEnum undefined)
```

If we don't want `f` to fail when given `toEnum undefined`, we need to statically ensure that `f` is a constant function, and thus we use `Tagged` for it.

All in all, after rereading that explanation I must say that it's not very good.

**Comment by neongreen** [comment]
> why is this not a valid candidate?

It is, but the whole point is that we want `from enum` to work out of the box instead of writing `enum_rev` manually. So, at some point `enum` would _have_ to be run with _some_ argument, and in lens-over-tea I show that when you try to think about how `from` would run `enum`, you can derive isomorphisms from that.
